[jenkins]
172.31.86.239 ansible_ssh_user='ec2-user'

[nginx]
172.31.94.243 ansible_ssh_user='ec2-user'

[sonarqube]
<SonarQube-Private-IP-Address>

[artifact_repository]
<Artifact_repository-Private-IP-Address>