pipeline {
    agent any

     parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    }
  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    stage('package') {
      steps {
        script {
          sh 'echo "This is the package stage"'
        }
      }
    }
    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deployment stage"'
        }
      }
    }
    stage('cleanup') {
      steps {
        script {
          sh 'echo "clean-up stage ni"'
        }
      }
    }
    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
                  }
      }
    }
    }
}