 pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Package') {
        steps {
          script {
            sh 'echo "Packing stage"'
          }
        }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deployment"'
        }
      }
    }

    stage('cleanup') {
      steps {
        script {
          sh 'echo "clean up"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    }
}
